// src/routes/femicide/src/components/Nav.tsx
import { useState } from "react";

const links: [string, string][] = [
  ["/#about", "About"],
  ["/#team", "Team"],
  ["/#stories", "Stories"],
  ["/#contact", "Contact"],
];

export default function Nav() {
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <nav className='fixed top-0 left-0 right-0 z-50 bg-paper border-b-0 border-ink'>
      <div className='flex items-center justify-between px-6 md:px-12 py-4'>
        <a
          href='/'
          className='font-display font-bold text-base tracking-widest uppercase text-ink no-underline'
        >
          The <span className='italic text-rust'>Granule</span>
        </a>

        {/* desktop links */}
        <ul className='hidden md:flex gap-10 list-none m-0 p-0'>
          {links.map(([href, label]) => (
            <li key={href}>
              <a
                href={href}
                className='font-mono text-base tracking-[0.14em] uppercase text-ink no-underline border-b border-transparent hover:border-rust hover:text-rust transition-colors duration-200'
              >
                {label}
              </a>
            </li>
          ))}
        </ul>

        {/* hamburger */}
        <button
          className='md:hidden flex flex-col gap-1.25 bg-transparent border-none cursor-pointer p-1'
          onClick={() => setMenuOpen((o) => !o)}
          aria-label='Toggle menu'
        >
          <span
            className={`block w-6 h-px bg-ink transition-all duration-200 ${menuOpen ? "rotate-45 translate-y-1.5" : ""}`}
          />
          <span
            className={`block w-6 h-px bg-ink transition-all duration-200 ${menuOpen ? "opacity-0" : ""}`}
          />
          <span
            className={`block w-6 h-px bg-ink transition-all duration-200 ${menuOpen ? "-rotate-45 -translate-y-1.5" : ""}`}
          />
        </button>
      </div>

      {/* mobile dropdown */}
      {menuOpen && (
        <div className='md:hidden absolute top-full left-0 right-0 bg-paper border-b-2 border-ink'>
          <ul className='list-none m-0 p-0 flex flex-col'>
            {links.map(([href, label]) => (
              <li key={href} className='border-b border-ink/10'>
                <a
                  href={href}
                  onClick={() => setMenuOpen(false)}
                  className='block font-mono text-[0.72rem] tracking-[0.16em] uppercase text-ink no-underline px-6 py-4 hover:text-rust hover:bg-paper-dark transition-colors duration-150'
                >
                  {label}
                </a>
              </li>
            ))}
          </ul>
        </div>
      )}
    </nav>
  );
}

// src/lib/components/Nav.svelte
<script lang="ts">
  let menuOpen = false;
  function closeMenu() {
    menuOpen = false;
  }

  let { isFixed = true } = $props();
</script>

<div>
  <!-- ───────────── NAV ───────────── -->
  <nav
    class={`${isFixed ? "fixed" : ""} top-0 left-0 right-0 z-50 bg-paper border-b-2 border-ink`}
  >
    <div class="flex items-center justify-between px-6 md:px-12 py-4">
      <a
        href="/"
        class="font-display font-bold text-base tracking-widest uppercase text-ink no-underline"
      >
        The <span class="italic text-rust">Granule</span>
      </a>

      <!-- desktop links -->
      <ul class="hidden md:flex gap-10 list-none m-0 p-0">
        {#each [["/#about", "About"], ["/#team", "Team"], ["/#stories", "Stories"], ["/#contact", "Contact"]] as [href, label]}
          <li>
            <a
              {href}
              class="font-mono text-base tracking-[0.14em] uppercase text-ink no-underline border-b border-transparent hover:border-rust hover:text-rust transition-colors duration-200"
            >
              {label}
            </a>
          </li>
        {/each}
      </ul>

      <!-- hamburger -->
      <button
        class="md:hidden flex flex-col gap-[5px] bg-transparent border-none cursor-pointer p-1"
        onclick={() => (menuOpen = !menuOpen)}
        aria-label="Toggle menu"
      >
        <span
          class="block w-6 h-px bg-ink transition-all duration-200"
          class:rotate-45={menuOpen}
          class:translate-y-[6px]={menuOpen}
        ></span>
        <span
          class="block w-6 h-px bg-ink transition-all duration-200"
          class:opacity-0={menuOpen}
        ></span>
        <span
          class="block w-6 h-px bg-ink transition-all duration-200"
          class:-rotate-45={menuOpen}
          class:-translate-y-[6px]={menuOpen}
        ></span>
      </button>
    </div>

    <!-- mobile dropdown -->
    <div
      class="mobile-menu md:hidden absolute top-full left-0 right-0 bg-paper border-b-2 border-ink"
      class:open={menuOpen}
    >
      <ul class="list-none m-0 p-0 flex flex-col">
        {#each [["#about", "About"], ["#team", "Team"], ["#stories", "Stories"], ["#contact", "Contact"]] as [href, label]}
          <li class="border-b border-ink/10">
            <a
              {href}
              onclick={closeMenu}
              class="block font-mono text-[0.72rem] tracking-[0.16em] uppercase text-ink no-underline px-6 py-4 hover:text-rust hover:bg-paper-dark transition-colors duration-150"
            >
              {label}
            </a>
          </li>
        {/each}
      </ul>
    </div>
  </nav>
</div>
